apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
  name: login
spec:
  replicas: {{ .Values.replicas.login }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: login
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: login
    spec:
      containers:
        - args:
            - login
          image: {{ .Values.sdcImage }}
          name: login
          env:
            - name: ROCKY_OOD_PASS
              valueFrom:
                secretKeyRef:
                  name: htdbm-secret
                  key: password
          ports:
            - containerPort: 22
            - containerPort: 80
          volumeMounts:
            - mountPath: {{ .Values.nfs.mountPath }}
              name: slurm-jobdir
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
            - mountPath: /tempmounts/munge.key
              name: munge-key-secret
              subPath: munge.key
            - mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              name: sshd-config-configmap
            - name: authorized-keys
              mountPath: /tempmounts/authorized_keys
              subPath: authorized_keys
            - name: ood-portal
              mountPath: /etc/ood/config/ood_portal.yml
              subPath: ood_portal.yml
            - name: httpd-config
              mountPath: /etc/httpd/conf/httpd.conf
              subPath: httpd.conf
            - name: cluster-config
              mountPath: /etc/ood/config/clusters.d/ood-cluster-config.yml
              subPath: ood-cluster-config.yml
          resources: {}
      hostname: login
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.nfs.claimName }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: sshd-config-configmap
          configMap:
            name: {{ .Values.configmaps.sshdConfig }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
        - name: authorized-keys
          configMap:
            name: {{ .Values.configmaps.authorizedKeys }}
        - name: cluster-config
          configMap:
            name: cluster-config
        - name: ood-portal
          configMap:
            name: ood-portal-configmap
        - name: httpd-config
          configMap:
            name: httpd-configmap
