apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
  name: slurmd
spec:
  replicas: {{ .Values.replicas.slurmd }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmd
  serviceName: slurmd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmd
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: slurm
              app.kubernetes.io/component: slurmd
      containers:
        - args:
            - slurmd
          image: {{ .Values.slurmImage }}
          name: slurmd
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
            - mountPath: {{ .Values.nfs.mountPath }}
              name: slurm-jobdir
            - mountPath: /tempmounts/munge.key
              name: munge-key-secret
              subPath: munge.key
          securityContext:
            privileged: true
      dnsConfig:
        searches:
          - slurmd.default.svc.cluster.local
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: {{ .Values.nfs.claimName }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
